const DB_NAME='legal_cases_pwa', DB_VER=1, STORE='tables';
const labels={'بيانات الموكلين':'الموكلون','حركة الدعوى':'حركة الدعوى / الجلسات','مراحل الدعوى':'مراحل الدعوى','حساب الدعوى':'حساب الدعوى','expence move':'المصروفات','حكم النقض':'أحكام النقض','المحامى':'المحامون','مستندات الدعوى':'مستندات الدعوى','صفة الموكل':'صفات الموكلين','نوع القضيه':'أنواع القضايا','نسخة من بيانات الموكلين':'نسخة بيانات الموكلين','DATA':'DATA','Reports':'التقارير','expence date':'تواريخ المصروفات','sec':'sec','Counter LAC':'Counter LAC','Counter Table':'Counter Table'};
const app=document.getElementById('app'); let db, state={view:'home',table:'بيانات الموكلين',search:'',page:1,open:false,edit:null};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'name'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function getAll(){return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(x){return new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(x);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function init(){db=await openDB();let all=await getAll();if(!all.length){for(const [name,x] of Object.entries(window.INITIAL_DATA))await put({name,...x});toast('تم استيراد بيانات Access إلى الهاتف');}render();if('serviceWorker' in navigator && location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});}
function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
async function tableData(name){return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(name);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function nav(name){state.view=name;state.page=1;state.search='';state.open=false;render()}
async function render(){const all=await getAll();const current=state.view==='home';app.innerHTML=`<div class="app"><div class="top"><button class="btn" onclick="state.open=true;render()">☰</button><div><h1>نظام القضايا المنظورة</h1><small>بيانات Access محفوظة محليًا على الجهاز</small></div><button class="btn install" id="install">تثبيت</button></div><div class="overlay ${state.open?'show':''}" onclick="state.open=false;render()"></div><aside class="side ${state.open?'open':''}"><button class="nav ${current?'active':''}" onclick="nav('home')">🏠 لوحة التحكم</button>${all.map(t=>`<button class="nav ${state.view===t.name?'active':''}" onclick="nav(${JSON.stringify(t.name)})">${labels[t.name]||t.name}</button>`).join('')}</aside><main class="main">${current?home(all):await tableView()}</main></div>`;setupInstall();}
function home(all){const wanted=['بيانات الموكلين','حركة الدعوى','مراحل الدعوى','حساب الدعوى'];return `<div class="panel"><h2>نظام القضايا المنظورة</h2><p class="muted">هذه النسخة تعمل محليًا على الهاتف. أي سجل تضيفه أو تعدله يُحفظ داخل الجهاز.</p></div><div class="cards">${wanted.map(n=>{const t=all.find(x=>x.name===n);return t?`<div class="card"><span>${labels[n]||n}</span><strong>${t.rows.length.toLocaleString('ar-YE')}</strong><span class="muted">سجل محفوظ</span></div>`:''}).join('')}</div><div class="panel"><h3>الجداول والبيانات</h3><div class="tablewrap"><table><thead><tr><th>الجدول</th><th>السجلات</th><th>الحقول</th><th></th></tr></thead><tbody>${all.map(t=>`<tr><td>${esc(labels[t.name]||t.name)}</td><td>${t.rows.length.toLocaleString('ar-YE')}</td><td>${t.columns.length}</td><td><button class="btn" onclick="nav(${JSON.stringify(t.name)})">فتح</button></td></tr>`).join('')}</tbody></table></div></div>`}
async function tableView(){const t=await tableData(state.view);if(!t)return '<div class="empty">الجدول غير موجود</div>';const q=state.search.trim().toLowerCase();const rows=t.rows.filter(r=>!q||t.columns.some(c=>String(r[c]??'').toLowerCase().includes(q)));const size=25,total=rows.length,pages=Math.max(1,Math.ceil(total/size));state.page=Math.min(state.page,pages);const pageRows=rows.slice((state.page-1)*size,state.page*size);return `<div class="panel"><div class="toolbar"><input class="search" placeholder="ابحث في جميع الحقول..." value="${esc(state.search)}" oninput="state.search=this.value;state.page=1;render()"><button class="btn primary" onclick="editRow()">＋ إضافة سجل</button><button class="btn" onclick="backup()">💾 نسخ احتياطي</button><button class="btn" onclick="window.print()">🖨️ طباعة</button></div><h2>${esc(labels[t.name]||t.name)}</h2><div class="tablewrap"><table><thead><tr>${t.columns.map(c=>`<th>${esc(c)}</th>`).join('')}<th class="no-print">إجراءات</th></tr></thead><tbody>${pageRows.map((r,i)=>`<tr>${t.columns.map(c=>`<td>${esc(r[c])}</td>`).join('')}<td class="no-print"><button class="btn" onclick='editRow(${JSON.stringify(r).replace(/'/g,"&#39;")})'>تعديل</button> <button class="btn danger" onclick='deleteRow(${JSON.stringify(r).replace(/'/g,"&#39;")})'>حذف</button></td></tr>`).join('')||`<tr><td colspan="${t.columns.length+1}"><div class="empty">لا توجد نتائج</div></td></tr>`}</tbody></table></div><div class="pager"><span>الإجمالي: ${total.toLocaleString('ar-YE')}</span><div><button class="btn" ${state.page<=1?'disabled':''} onclick="state.page--;render()">السابق</button><b>${state.page} / ${pages}</b><button class="btn" ${state.page>=pages?'disabled':''} onclick="state.page++;render()">التالي</button></div></div></div>${state.edit?modal(t,state.edit):''}`}
function modal(t,row){return `<div class="modal"><div class="box"><h3>${row.__new?'إضافة':'تعديل'} سجل في ${esc(labels[t.name]||t.name)}</h3><div class="grid">${t.columns.map(c=>`<div class="field"><label>${esc(c)}<input id="f_${btoa(unescape(encodeURIComponent(c))).replace(/=/g,'')}" value="${esc(row[c])}" data-col="${esc(c)}"></label></div>`).join('')}</div><div class="actions"><button class="btn" onclick="state.edit=null;render()">إلغاء</button><button class="btn primary" onclick="saveRow()">حفظ</button></div></div></div>`}
async function editRow(row){const t=await tableData(state.view);state.edit=row?{...row}:Object.fromEntries(t.columns.map(c=>[c,'']));if(!row)state.edit.__new=true;render()}
async function saveRow(){const t=await tableData(state.view);const inputs=[...document.querySelectorAll('[data-col]')];const obj={};inputs.forEach(i=>obj[i.dataset.col]=i.value);if(state.edit.__new){delete state.edit.__new;t.rows.push(obj)}else{const pk=t.columns[0];const idx=t.rows.findIndex(r=>String(r[pk])===String(state.edit[pk]));if(idx>=0)t.rows[idx]=obj;else t.rows.push(obj)}await put(t);state.edit=null;toast('تم حفظ السجل');render()}
async function deleteRow(row){if(!confirm('هل أنت متأكد من حذف هذا السجل؟'))return;const t=await tableData(state.view),pk=t.columns[0];t.rows=t.rows.filter(r=>String(r[pk])!==String(row[pk]));await put(t);toast('تم حذف السجل');render()}
async function backup(){const all=await getAll();const blob=new Blob([JSON.stringify(all,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='نسخة_احتياطية_القضايا_'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href);toast('تم تجهيز النسخة الاحتياطية')}
let deferred;function setupInstall(){const b=document.getElementById('install');if(deferred&&b){b.style.display='block';b.onclick=async()=>{deferred.prompt();await deferred.userChoice;deferred=null;b.style.display='none'}}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;setupInstall()});init();
